
#Yonatan
#server:
 #   port: 9093


#spring:
  #  profiles:
   #      active: dev
   # application:
   #    name: USER-SERVICE
   # datasource:
   #     driver-class-name : com.mysql.cj.jdbc.Driver
   # jpa:
   #     hibernate:
    #      ddl-auto: update 
    #    show-sql: true
     #   database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
    port: 9093


eureka:
   client:
     service-url:
          defaultZone: http://localhost:8761/eureka
   instance:
    # instanceId: ${USER-SERVICE}
     #appname: USER-SERVICE
     #hostname: USER-SERVICE


spring:
   application:
          name: USER-SERVICE
   datasource:
        url: jdbc:mysql://localhost:3306/userdb2
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        
   jpa: 
     hibernate:
         ddl-auto: update
     show-sql: true
     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect